# Generated by Django 5.0.6 on 2026-09-07 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='diagrams.project')),
            ],
        ),
        migrations.CreateModel(
            name='UMLClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('CLASS', 'Clase'), ('ABSTRACT', 'Clase abstracta'), ('INTERFACE', 'Interfaz'), ('ENUM', 'Enum')], default='CLASS', max_length=20)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='diagrams.diagram')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('ASSOCIATION', 'Asociación'), ('AGGREGATION', 'Agregación'), ('COMPOSITION', 'Composición'), ('INHERITANCE', 'Herencia'), ('REALIZATION', 'Realización'), ('DEPENDENCY', 'Dependencia')], default='ASSOCIATION', max_length=20)),
                ('multiplicity_source', models.CharField(blank=True, default='1', max_length=20)),
                ('multiplicity_target', models.CharField(blank=True, default='1', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='diagrams.diagram')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='diagrams.umlclass')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='diagrams.umlclass')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('return_type', models.CharField(default='void', max_length=100)),
                ('visibility', models.CharField(choices=[('PUBLIC', '+'), ('PRIVATE', '-'), ('PROTECTED', '#'), ('PACKAGE', '~')], default='PUBLIC', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=list)),
                ('is_static', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uml_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='diagrams.umlclass')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(default='String', max_length=100)),
                ('visibility', models.CharField(choices=[('PUBLIC', '+'), ('PRIVATE', '-'), ('PROTECTED', '#'), ('PACKAGE', '~')], default='PRIVATE', max_length=20)),
                ('is_static', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uml_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='diagrams.umlclass')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
