# Generated by Django 5.0.6 on 2026-09-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umlclass',
            name='height',
            field=models.FloatField(default=140),
        ),
        migrations.AddField(
            model_name='umlclass',
            name='width',
            field=models.FloatField(default=220),
        ),
    ]
