# Generated by Django 5.0.6 on 2026-09-15 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0003_projectmember_projectshare_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Solo lectura'), ('EDITOR', 'Puede editar'), ('SHARER', 'Puede compartir'), ('ADMIN', 'Administrador')], default='VIEWER', max_length=15),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Solo lectura'), ('EDITOR', 'Puede editar'), ('SHARER', 'Puede compartir'), ('ADMIN', 'Administrador')], default='VIEWER', max_length=15),
        ),
        migrations.CreateModel(
            name='DiagramVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('label', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagram_versions', to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='diagrams.diagram')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='diagramversion',
            constraint=models.UniqueConstraint(fields=('diagram', 'version_number'), name='unique_diagram_version'),
        ),
    ]
