# Generated by Django 5.0.6 on 2026-09-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0005_diagramversion_is_automatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='es_pk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='es_unico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='longitud',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='nullable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='nombre_campo_destino',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relation',
            name='nombre_campo_origen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
