"""HTTP integration check for the project generated by demo_step3.py.

Uses only the standard library; writes data exclusively to the generated demo API.
"""
import json
import os
import uuid
from urllib.request import Request, urlopen
from urllib.error import HTTPError

BASE = os.environ.get("GENERATED_API_URL", "http://127.0.0.1:8080")
TOKEN = None


def request(method, path, body=None, expected=200):
    headers = {"Content-Type": "application/json"}
    if TOKEN:
        headers["Authorization"] = "Bearer " + TOKEN
    req = Request(BASE + path, data=None if body is None else json.dumps(body).encode(),
        headers=headers, method=method)
    try:
        with urlopen(req, timeout=30) as response:
            status, payload = response.status, response.read()
    except HTTPError as error:
        status, payload = error.code, error.read()
    assert status == expected, f"{method} {path}: expected {expected}, got {status}: {payload.decode()}"
    return json.loads(payload) if payload else None


def authenticate(username=None, password=None):
    global TOKEN
    credentials = {
        "username": username or os.environ.get("APP_ADMIN_USERNAME", "admin"),
        "password": password or os.environ.get("APP_ADMIN_PASSWORD", "change-this-local-password"),
    }
    TOKEN = request("POST", "/api/auth/login", credentials)["token"]
    return TOKEN


def run():
    if not TOKEN:
        authenticate()
    tag = uuid.uuid4().hex[:12]
    perfil = request("POST", "/api/perfils", {"descripcion": "Perfil " + tag}, 201)
    uuid.UUID(perfil["clavePerfil"])
    cliente_body = {"nombre": "Cliente " + tag, "email": tag + "@example.test", "perfilId": perfil["clavePerfil"]}
    cliente = request("POST", "/api/clientes", cliente_body, 201)
    cid = cliente["codigoCliente"]
    assert cliente["perfilId"] == perfil["clavePerfil"]
    assert request("GET", "/api/perfils/" + perfil["clavePerfil"])["clienteId"] == cid
    etiqueta = request("POST", "/api/etiquetas", {"codigo": tag, "nombre": "Urgente"}, 201)
    request("POST", "/api/etiquetas", {"codigo": tag, "nombre": "Duplicada"}, 409)
    pedido_body = {"total": 12.5, "fecha": "2026-01-01", "creado": "2026-01-01T12:00:00", "pagado": False, "clienteId": cid, "etiquetasIds": [etiqueta["codigo"]]}
    pedido = request("POST", "/api/pedidos", pedido_body, 201)
    pid = pedido["codigoPedido"]
    assert pedido["clienteId"] == cid and pedido["etiquetasIds"] == [tag]
    assert pid in request("GET", f"/api/clientes/{cid}")["pedidosIds"]
    assert pid in request("GET", f"/api/etiquetas/{tag}")["pedidosIds"]
    assert any(value["codigoCliente"] == cid for value in request("GET", "/api/clientes")["content"])
    subordinate = request("POST", "/api/clientes", {"nombre": "Subordinado", "supervisorId": cid}, 201)
    sid = subordinate["codigoCliente"]
    assert sid in request("GET", f"/api/clientes/{cid}")["subordinadosIds"]
    request("POST", "/api/clientes", {"codigoCliente": cid, "nombre": "No permitido"}, 400)
    request("POST", "/api/clientes", {"nombre": "Duplicado", "email": cliente_body["email"]}, 409)
    request("POST", "/api/clientes", {}, 400)
    request("POST", "/api/clientes", {"nombre": "x" * 81}, 400)
    request("GET", "/api/pedidos/invalid", expected=400)
    request("GET", "/api/perfils/not-a-uuid", expected=400)
    request("GET", "/api/pedidos/2147483647", expected=404)
    request("POST", "/api/pedidos", {"total": 1, "clienteId": 9223372036854775807}, 404)
    request("POST", "/api/pedidos", {"total": 1, "etiquetasIds": [None]}, 400)
    request("PUT", f"/api/pedidos/{pid}", {**pedido_body, "codigoPedido": pid + 1}, 400)
    # A failed relationship change must roll back scalar changes as well.
    request("PUT", f"/api/pedidos/{pid}", {**pedido_body, "total": 99, "clienteId": 9223372036854775807}, 404)
    assert request("GET", f"/api/pedidos/{pid}")["total"] == 12.5
    actualizado = request("PUT", f"/api/pedidos/{pid}", {"total": 20, "clienteId": cid})
    assert actualizado["codigoPedido"] == pid and actualizado["etiquetasIds"] == [tag]
    request("DELETE", f"/api/clientes/{cid}", expected=409)
    request("DELETE", f"/api/pedidos/{pid}", expected=204)
    request("GET", f"/api/pedidos/{pid}", expected=404)
    request("DELETE", f"/api/etiquetas/{tag}", expected=204)
    request("DELETE", f"/api/clientes/{sid}", expected=204)
    request("DELETE", f"/api/clientes/{cid}", expected=204)
    request("DELETE", "/api/perfils/" + perfil["clavePerfil"], expected=204)
    openapi = request("GET", "/v3/api-docs")
    assert "/api/clientes" in openapi["paths"]
    print("PASS: CRUD, four PK types, 1-N, 1-1, N-N, self-reference, validation, 404, 409, transactional rollback and OpenAPI.")


if __name__ == "__main__":
    run()
